server:
  port: 8081
spring:
  application:
    name: auth-service
  datasource:
    url: jdbc:postgresql://localhost:5432/auth_db
    username: postgres
    password: VolnaMuskan
  jpa:
    hibernate:
      ddl-auto: validate
  flyway:
    enabled: true
    baseline-on-migrate: true
management:
  endpoints:
    web:
      exposure:
        include: health,info
app:
  jwt:
    secret: "RTp40Z/7pbRiwArwWjS3Xch9PgKe7LhO1j7u+BFc2Xs="
    expiration-ms: 3600000
