version: '3.8'

services:
  user-db:
    image: postgres:15-alpine
    container_name: volna-user-db
    environment:
      POSTGRES_DB: volna_user_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: VolnaMuskan
    ports:
      - "5432:5432"
    volumes:
      - volna_user_db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  user-service:
    build: .
    container_name: volna-user-service
    ports:
      - "8082:8082"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://user-db:5432/volna_user_db
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: VolnaMuskan
      JWT_SECRET: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
    depends_on:
      user-db:
        condition: service_healthy

volumes:
  volna_user_db_data:
