CREATE TABLE auth_users (
 id UUID PRIMARY KEY,
 full_name VARCHAR(150) NOT NULL,
 email VARCHAR(255) NOT NULL UNIQUE,
 phone_number VARCHAR(20) NOT NULL UNIQUE,
 password_hash VARCHAR(255) NOT NULL,
 role VARCHAR(50) NOT NULL,
 enabled BOOLEAN NOT NULL DEFAULT TRUE,
 created_at TIMESTAMP WITH TIME ZONE NOT NULL,
 updated_at TIMESTAMP WITH TIME ZONE NOT NULL
);